require('giovanni.plugins-setup')
require('giovanni.core.options')
require('giovanni.core.keymaps')
require('giovanni.core.colorscheme')
require('giovanni.plugins.comment')
require('giovanni.plugins.nvim-tree')
